# netlify.toml

[build]
  functions = "netlify/functions"


[[functions.headline_analyzer]]
  # This path is relative to the function's directory root
  # (netlify/functions/headline_analyzer/).
  # So, "graph_config.json" means it will take the file from
  # netlify/functions/headline_analyzer/graph_config.json
  # and include it at the root of the deployment package (/var/task/graph_config.json).
  included_files = ["graph_config.json"]